### ISSUE TITLE
ERROR: dependency ‘TeachingDemos’

### ISSUE THREAD

**Issue by alextamburino** [BaderLab/scClustViz#16]
Hi,
Thanks for the excellent work and data availability.
I'm getting the following error regarding a TeachingDemos dependency.
Can you please clarify where this package is located or an alternate solution.

Thanks,
Alex

> devtools::install_github("BaderLab/scClustViz")
Downloading GitHub repo BaderLab/scClustViz@master
from URL https://api.github.com/repos/BaderLab/scClustViz/zipball/master
Installing scClustViz
**ERROR: dependency ‘TeachingDemos’ is not available for package ‘scClustViz’**
Installation failed: Command failed (1)

**Comment by innesbre** [comment]
TeachingDemos is an R package on cran (https://cran.r-project.org/package=TeachingDemos).  This error probably occurred due to a temporary drop in internet access, and if you run the installation again with internet access it should resolve.

**Comment by alextamburino** [comment]
You are correct. It was a connection issue. Thanks!
