### ISSUE TITLE
seurat v3 concerns again

### ISSUE THREAD

**Issue by whtns** [BaderLab/scClustViz#30]
Hey again,

I'm still having issues with Seurat v3 as in #27 

I'm emailing you a copy of the minimal test dataset and rmarkdown. There seems to be an issue accessing embeddings? The errors I'm getting: 

`## Error in CalcSCV(seu, clusters, exponent = exp(1)): Input data object must be one of: seurat, SingleCellExperiment.`

`## Error in slot(eb1S@reductions[[tolower(DRtype)]], "cell.embeddings"): object 'eb1S' not found`

**Comment by innesbre** [comment]
I didn't notice that they changed the class name from "seurat" to "Seurat".  Thanks for sending the demo data.  I've added support for various assay slots as well, so you can choose whether to use your intergrated data or the RNA slot from the Seurat Assays.
