### ISSUE TITLE
Better file names for GOI overlay plots

### ISSUE THREAD

**Issue by gaelder** [BaderLab/scClustViz#35]
Hi Brendan,

Throwing this issue here as a friendly reminder that it would be greatly appreciated! When you have a moment could you update the filename for goi downloads to name the gene selected since generally I'm downloading 10+ of these files in quick succession!

e.g: name this downloaded file as CD3E.pdf (sample-name-CD3E.pdf) instead of goi1.pdf
![Screenshot from 2019-07-25 11-17-22](https://user-images.githubusercontent.com/28417535/61886732-3a880700-aece-11e9-9903-6b4931ceba59.png)

**Comment by innesbre** [comment]
Done!
