### ISSUE TITLE
Error in get(lfc[X])[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by ankushs0128** [BaderLab/scClustViz#45]
Hi, 

I´m getting an error on the merged dataset, however runshiny is working fine for individual runs
The error i'm getting after following the scClustviz vignette: 

```
**Error in get(lfc[X])[[1]] : subscript out of bounds**
5.
is(get(lfc[X])[[1]])
4.
FUN(X[[i]], ...)
3.
lapply(X = X, FUN = FUN, ...)
2.
sapply(seq_along(lfc), function(X) { if (is(get(lfc[X]))[1] %in% findMethodSignatures(getExpr)) { return("inD") } ...
1.
runShiny(filePath = "Merged_runsClustViz.RData", outPath = "./", annotationDB = "org.Hs.eg.db", imageFileType = "png")

```
Highly appreciate any pointers to rectify the error!

Thanks in Advance

**Comment by innesbre** [comment]
Would you be comfortable sending me an example of the dataset that breaks things?  You can upload it as an RData file here: https://www.dropbox.com/request/5w5ptx6MwNxVHRTFd8A9

**Comment by ankushs0128** [comment]
Restarting R and re installing Shiny solved the problem !! 

thanks for your help
