### ISSUE TITLE
A question on using scClustViz on integrated data (Seurat)

### ISSUE THREAD

**Issue by martinfalck** [BaderLab/scClustViz#47]
Hi!

Satijalab(Seurat) recommend using the RNA assay when exploring markers and differential expression. But in their vignettes that do integration between datasets, or comparison between control and treatment, they use the "integrated" dataset assay for pca, neighbors, and clustering. 

So as far as I understood this, scClustViz would run best with its iterative clustering using the integrated assay but for the marker analysis (which I find very useful in the shiny app) it should run on the RNA assay. How can I solve this? 

I'll include the code I use for iterative clustering below. Perhaps there is a way to have assaytype set to integrated for clustering and then somehow setting marker analysis to use RNA-counts, but I'm not sure how to do this. 

Thanks for all the great tools that you develop!

```{r}
max_seurat_resolution <- 1.5 # Stop at the max
output_filename <- paste0("./data/our_data/clustviz_clustering/",currentjob,"_.RData")
FDRthresh <- 0.01 # FDR threshold for statistical tests
min_num_DE <- 1
seurat_resolution <- 0.15 # Starting resolution is this plus the jump value below.
seurat_resolution_jump <- 0.05

sCVdata_list <- list()
DE_bw_clust <- TRUE

while(DE_bw_clust) {
  if (seurat_resolution >= max_seurat_resolution) { break }
  seurat_resolution <- seurat_resolution + seurat_resolution_jump 
  # ^ iteratively incrementing resolution parameter 
    pan_seurat <- FindClusters(pan_seurat,resolution=seurat_resolution,verbose=F)
    message(" ")
  message("------------------------------------------------------")
  message(paste0("--------  res.",seurat_resolution," with ",
                 length(levels(Idents(pan_seurat)))," clusters --------"))
  message("------------------------------------------------------")
    if (length(levels(Idents(pan_seurat))) <= 1) { 
    message("Only one cluster found, skipping analysis.")
    next 
  } 
  # ^ Only one cluster was found, need to bump up the resolution!
  
  if (length(sCVdata_list) >= 1) {
    temp_cl <- length(levels(Clusters(sCVdata_list[[length(sCVdata_list)]])))
    if (temp_cl == length(levels(Idents(pan_seurat)))) { 
      temp_cli <- length(levels(interaction(
        Clusters(sCVdata_list[[length(sCVdata_list)]]),
        Idents(pan_seurat),
        drop=T
      )))
      if (temp_cli == length(levels(Idents(pan_seurat)))) { 
        message("Clusters unchanged from previous, skipping analysis.")
        next 
      }
    }
  }
    curr_sCVdata <- CalcSCV(
    inD=pan_seurat,
    assayType="RNA",
    assaySlot = "counts",
    cl=Idents(pan_seurat), 
    # ^ your most recent clustering results get stored in the Seurat "ident" slot
    exponent=NA, 
    pseudocount=NA,
    DRthresh=0.1,
    DRforClust="umap",
    calcSil=T,
    calcDEvsRest=T,
    calcDEcombn=T
  )
  
  DE_bw_NN <- sapply(DEneighb(curr_sCVdata,FDRthresh),nrow)
  # ^ counts # of DE genes between neighbouring clusters at your selected FDR threshold
  message(paste("Number of DE genes between nearest neighbours:",min(DE_bw_NN)))
  
  if (min(DE_bw_NN) < min_num_DE) { DE_bw_clust <- FALSE }
  # ^ If no DE genes between nearest neighbours, don't loop again.
  
  sCVdata_list[[paste0("res.",seurat_resolution)]] <- curr_sCVdata
}

save(sCVdata_list,pan_seurat,file=output_filename)
```

**Comment by innesbre** [comment]
Hi Martin,
Glad you're finding this tool useful!  
To cluster using the integrated data in the Seurat object, simply ensure that `DefaultAssay(pan_seurat)` is set to "integrated" - That way when Seurat runs `FindClusters`, it is doing so on the integrated object.  The differential gene expression testing for identifying marker genes and evaluating cluster resolution (by # of DE genes between clusters) happens during the `CalcSCV` function.  To use the normalized gene abundances in the Seurat RNA assay slot, you'll want to specify 
```
CalcSCV(
  inD=pan_seurat
  assayType="RNA",
  assaySlot="data",
  ...
)
```
As you've currently set it, you're passing the raw counts to the Wilcoxon rank-sum test, rather than normalized counts.  I _don't think_ that that's considered best practice, but frankly there's a much more fundamental problem with evaluating clustering and identifying marker on the basis of differential gene expression from clustered data.  As outlined by the authors of these papers (https://doi.org/10.1016/j.cels.2019.07.012 & https://www.lucylgao.com/clusterpval/index.html), doing hypothesis testing on the same data you used to define the hypothesis violates some fundamental assumptions.  I think its fair to say that while the p-values you get are terribly overconfident, the rank order of differential abundance should still be true and the visualizations of "marker gene" distribution across clusters should allow you to critically evaluate the proposed marker genes.

**Comment by martinfalck** [comment]
Hi!

Nice answer! 

Yes I was going through the tool help one more time, last time I used it was on SCT integrated samples so now I had forgotten to swap quite some things, like the exponent, The code I used last time is in line with what you recommend. Sometimes writing the question clears up the path to an solution. It was nice to have a thorough answer to lift any doubts I had. 

Thanks and have a nice weekend!



sCVdata_list <- list()
DE_bw_clust <- TRUE

while(DE_bw_clust) {
  if (seurat_resolution >= max_seurat_resolution) { break }
  seurat_resolution <- seurat_resolution + seurat_resolution_jump 
  # ^ iteratively incrementing resolution parameter 
    pan_seurat <- FindClusters(pan_seurat,resolution=seurat_resolution,verbose=F)
    message(" ")
  message("------------------------------------------------------")
  message(paste0("--------  res.",seurat_resolution," with ",
                 length(levels(Idents(pan_seurat)))," clusters --------"))
  message("------------------------------------------------------")
    if (length(levels(Idents(pan_seurat))) <= 1) { 
    message("Only one cluster found, skipping analysis.")
    next 
  } 
  # ^ Only one cluster was found, need to bump up the resolution!
  
  if (length(sCVdata_list) >= 1) {
    temp_cl <- length(levels(Clusters(sCVdata_list[[length(sCVdata_list)]])))
    if (temp_cl == length(levels(Idents(pan_seurat)))) { 
      temp_cli <- length(levels(interaction(
        Clusters(sCVdata_list[[length(sCVdata_list)]]),
        Idents(pan_seurat),
        drop=T
      )))
      if (temp_cli == length(levels(Idents(pan_seurat)))) { 
        message("Clusters unchanged from previous, skipping analysis.")
        next 
      }
    }
  }
    curr_sCVdata <- CalcSCV(
    inD=pan_seurat,
    assayType="RNA",
    assaySlot = "data",
    cl=Idents(pan_seurat), 
    # ^ your most recent clustering results get stored in the Seurat "ident" slot
    exponent=exp(1), 
    pseudocount=1,
    DRthresh=0.1,
    DRforClust="pca",
    calcSil=T,
    calcDEvsRest=T,
    calcDEcombn=T
  )
  
  DE_bw_NN <- sapply(DEneighb(curr_sCVdata,FDRthresh),nrow)
  # ^ counts # of DE genes between neighbouring clusters at your selected FDR threshold
  message(paste("Number of DE genes between nearest neighbours:",min(DE_bw_NN)))
  
  if (min(DE_bw_NN) < min_num_DE) { DE_bw_clust <- FALSE }
  # ^ If no DE genes between nearest neighbours, don't loop again.
  
  sCVdata_list[[paste0("res.",seurat_resolution)]] <- curr_sCVdata
}
