### ISSUE TITLE
Installation error: syntax issue in deTest.R line 180

### ISSUE THREAD

**Issue by EDePasquale** [BaderLab/scClustViz#49]
When installing I get the following error: "Error in parse(outFile) : 
  /private/var/folders/bz/2k93vv6d30n3fkfbwjf0nyjsgw_94g/T/RtmpSEFALX/R.INSTALL126c958b36b76/scClustViz/R/deTest.R:180:16: unexpected symbol
179:                "The decision to stop testing depends on the results of caclDEcombn."
180:                sep"

I looked at lines 179 and 180 and it looks like there is a missing comma before the "sep" argument.

**Comment by innesbre** [comment]
Fixed! Sorry about that, thanks for finding it.
