### ISSUE TITLE
runShiny not working

### ISSUE THREAD

**Issue by ccnawrocki** [BaderLab/scClustViz#50]
I feel like I have followed the example code for using your shiny app to a tee, yet runShiny is not working. I keep getting the following error when I call runShiny(): 

Error in FUN(X[[i]], ...) : 
  Unexpected input object. Missing single-cell data object.

Could you please help? I will attach my R script below. 'norm' is a Seurat v3 object. Louvain clustering has been done and the sc RNA assay data is normalized and scaled. Attached is the script and the file for 'norm'.

[scClustViz.R.zip](https://github.com/BaderLab/scClustViz/files/9244654/scClustViz.R.zip)
[norm.h5seurat.zip](https://github.com/BaderLab/scClustViz/files/9244659/norm.h5seurat.zip)

**Comment by innesbre** [comment]
runShiny used to expect a list of sCVdata objects (the output of CalcAllSCV), and returned that (admittedly unhelpful) error if it couldn't find one.  I've updated it to accept a single sCVdata object (as you've done in your script, the output of CalcSCV), so if you reinstall scClustViz now your script should work as expected.

**Comment by innesbre** [comment]
Ah, looks like the problem is that you named your Seurat object `norm` which is also the name of a base function.  runShiny looks at the type of each loaded object to find the scRNAseq data file, and since `is(norm)` is a function, not a Seurat object, it isn't happy.  Try changing the name of the Seurat object to something that isn't a function name.

**Comment by ccnawrocki** [comment]
Thanks for getting back to me. I tried renaming the seurat object something random ("norm345"), but I am still getting the same error... Sorry to keep bothering you with this.

**Comment by innesbre** [comment]
The other possible error is that runShiny used to expect a list of sCVdata objects (the output of CalcAllSCV), and returned that (admittedly unhelpful) error if it couldn't find one. I've updated it to accept a single sCVdata object (as you've done in your script, the output of CalcSCV), so if you reinstall scClustViz now your script should work as expected.
