### ISSUE TITLE
Updated Ubuntu & R, unable to runShiny()

### ISSUE THREAD

**Issue by alexwskh** [BaderLab/scClustViz#52]
I recently had to update Ubuntu and R on our labs bioinformatics computer.  My PI was previously able to use the runShiny command from scClustCiz to open up and look at scRNASeq data. Files that were able to be opened previously (and any new files we've tried to make through the pipeline) are unable to be opened.

R Version: 4.3.1

```
library(Seurat)
library(scClustViz)

runShiny(filePath = "/home/bret/Madeline/MadelineRNAseq/RMS_8_MET_Feb2023/RMS_8_MET_Feb28.RData") #loading already existing pipeline output
```

And the error is:

Error in if (!grepl("^<!DOCTYPE html>|<html", lines, ignore.case = TRUE)) { : 
  argument is of length zero

It looks like the command partially executes as there is some objects in the workspace-but there's not interactive page that pops up-just the above error.

I'm not a programmer but I've some basic knowledge. Not sure if I'm missing something that needs to be installed on Linux or a package. Any help is appreciated!

Thanks,

Alex

**Comment by innesbre** [comment]
Fixed

**Comment by alexwskh** [comment]
Thank you so much.

I am able to launch from the previous RData files, so that's great. There are still some error messages being generated-I'm not sure if you're already aware of these given the "Please note", but they look similarly related to the length zero error that prevented launch. Here are some pictures of the issues as well as the R output... So I assume it is mostly/kind of working?

[cid:9b8198e5-ebe7-4d0f-80eb-1b91d8bc2539]
[cid:77285e5e-0869-4258-b60d-64b34e23aae1]

[cid:39ef501a-4d97-44ab-a334-fe7bb051a921]



> runShiny(filePath = "/home/bret/Madeline/MadelineRNAseq/RMS_8_MET_Feb2023/RMS_8_MET_Feb28.RData") #loading already existing pipeline output
Listening on http://127.0.0.1:4938
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$saveButton
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$clustSep
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$FDRthresh1
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>Warning: Error in h: error in evaluating the argument 'sCVd' in selecting a method for function 'Silhouette': attempt to select less than one element in get1index
  171: Silhouette
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$sil
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$MD_EmbDimX
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$MD_EmbDimY
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in .subset2: attempt to select less than one element in get1index
  103: ( function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, i, exact = exact)
  102: [[.data.frame
   99: renderUI
   98: func
   85: renderFunc
   84: output$tsneMDlog
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in h: error in evaluating the argument 'sCVd' in selecting a method for function 'Clusters': attempt to select less than one element in get1index
  100: Clusters
   99: renderUI
   98: func
   85: renderFunc
   84: output$cgLegend
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$GOI_EmbDimX
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$GOI_EmbDimY
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$saveButton2
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$addCellsA
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$addCellsB
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$removeCellsA
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$removeCellsB
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$DEsetName
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$calcDE
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$calcText
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$SelDE_EmbDimX
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderUI
   98: func
   85: renderFunc
   84: output$SelDE_EmbDimY
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  106: getEmb
   99: renderText
   98: func
   85: renderFunc
   84: output$cellsHovered
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderText
  98: func
  85: renderFunc
  84: output$textSetA
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderText
  98: func
  85: renderFunc
  84: output$textSetB
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in if: argument is of length zero
  99: renderText
  98: func
  85: renderFunc
  84: output$textOverlap
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>$rect
$rect$w
[1] 14.39366

$rect$h
[1] 0.1453458

$rect$left
[1] 19.90634

$rect$top
[1] 1.196277


$text
$text$x
[1] 21.52972

$text$y
[1] 1.123604


Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsne
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  206: <reactive>
  204: .func
  201: contextFunc
  200: env$runWith
  193: ctx$run
  192: self$.updateValue
  190: selClust
  189: <reactive>
  187: .func
  184: contextFunc
  183: env$runWith
  176: ctx$run
  175: self$.updateValue
  173: selCells
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$mdScatter
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in switch: EXPR must be a length 1 vector
  172: plot_mdBarplot
  171: plot_mdPerClust
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$mdFactor
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  99: renderUI
  98: func
  85: renderFunc
  84: output$DEgeneSlider
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>Warning: Error in if: argument is of length zero
  192: dotplotDEgenes
  191: <reactive>
  189: .func
  186: contextFunc
  185: env$runWith
  178: ctx$run
  177: self$.updateValue
  175: DEgenes
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$dotplot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in switch: EXPR must be a length 1 vector
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$clusterGenes
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  171: plot_GEboxplot
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$geneTest
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  102: <Anonymous>
  101: stop
  100: selClust   99: renderUI
   98: func
   85: renderFunc
   84: output$setScatterA
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in if: argument is of length zero
  102: <Anonymous>
  101: stop
  100: selClust
   99: renderUI
   98: func
   85: renderFunc
   84: output$setScatterB
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in if: argument is of length zero
  171: plot_compareClusts
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$setScatter
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in cut.default: 'x' must be numeric
  174: stop
  173: cut.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneSelDE
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in if: argument is of length zero
  175: <Anonymous>
  174: stop
  173: selCells
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$mdScatter
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in switch: EXPR must be a length 1 vector
  172: plot_mdBarplot
  171: plot_mdPerClust
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$mdFactor
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in cut.default: 'x' must be numeric
  174: stop
  173: cut.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneSelDE
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in :: argument of length 0
  175: FUN
  174: lapply
  171: plot_deDotplot
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$dotplot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsne
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>$rect
$rect$w
[1] 8.316722

$rect$h
[1] 0.1453458

$rect$left
[1] 25.98328

$rect$top
[1] 1.196277


$text
$text$x
[1] 26.92128

$text$y
[1] 1.123604


Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsne
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in [: subscript out of bounds
  174: <Anonymous>
  173: plot.default
  171: plot_tsne
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$tsneMD
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>



Alexander Weiss, MSc
Research Technologist
Peter Gilgan Centre for Research and Learning
The Hospital for Sick Children
686 Bay Street, 15.9420 Bay V



________________________________

**Comment by innesbre** [comment]
Does the app open a web browser and allow you to explore your data?

**Comment by alexwskh** [comment]
Those snapshots are from whatever window launches in R... If I click the open in browser option it looks much the same, but both seem to work after you toggle all of the input fields at least once as noted in the red text. I'm guessing it doesn't like "empty" values compared to "zero" values? Anyways, thank you so much for the quick fix.


Alexander Weiss, MSc
Research Technologist
Peter Gilgan Centre for Research and Learning
The Hospital for Sick Children
686 Bay Street, 15.9420 Bay V



________________________________
