### ISSUE TITLE
Select cells for selDE using metadata

### ISSUE THREAD

**Issue by innesbre** [BaderLab/scClustViz#9]
Metadata + clusters

**Comment by vincent-van-hoef** [comment]
Hi, Thanks for a great tool! Is this possible now? It would be nice to be able to compare gene expression in a certain cluster between for example different patients.

**Comment by innesbre** [comment]
Yes, if you go to the bottom of the interactive report (see ?runShiny), there's a section where you can select sets of cells to compare using metadata filters (hit the "add filter" button to include multiple filters) or click and drag cell selection.

**Comment by vincent-van-hoef** [comment]
Great, thanks! Must've overlooked that...
